### ISSUE TITLE
Hjælp Python fejl - opsætning af plugin i QGIS

### ISSUE THREAD

**Issue by muldalh** [Skadesokonomi/Udvikling#23]
Hej.

Jeg får en python fejl, når jeg vil lave forbindelse til Postgres databasen. Det er når jeg kommer til pkt. 4 nr 5 under overskriften Første gangs opsætning af plugin i QGIS i installations vejledningen. Fejlen jeg får er herunder

2022-06-23T09:45:31     WARNING    Traceback (most recent call last):
              File "C:\Users/B047831/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\eco_model\eco_model.py", line 716, in pbParameterResetClicked
              self.parmDict, hl = self.createParmDict(spd["Parametertable"], spd["Parameterkeyfield"], spd["Parameterkeyvalue"], spd["Parametervaluefield"])
              File "C:\Users/B047831/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\eco_model\eco_model.py", line 954, in createParmDict
              return pdict, [rec.fieldName(i) for i in range(rec.count()-1)]
             UnboundLocalError: local variable 'rec' referenced before assignment

Hvad gør jeg forkert ?
Jeg har vedhæftede et billede af hvordan det ser ud i mit QGIS.

![Udklip](https://user-images.githubusercontent.com/108058558/175262799-78b6353f-05b1-4bc5-b062-b850b4a32cbb.PNG)

Venlig hilsen
Morten

**Comment by bvthomsen** [comment]
@muldalh : Tak for meddelelsen (og for løsningen). Jeg har lavet en rettelse i eco_model.py, der fremadrettet (forhåbentlig) løser dette problem. 

Men under alle omstændigheder er det en god idé at kun bruge små bogstaver til schema, tabel og kolonnenavne i PostgreSQL.
Det gør læsbarheden af diverse SQL scripts meget bedre
