### ISSUE TITLE
Færdiggørelse af dokumentation

### ISSUE THREAD

**Issue by bvthomsen** [Skadesokonomi/Udvikling#7]
Der er nu lavet en kortfattet installationsvejledning. Men vejledning i opsætning af modeller og forespørgsler mangler . Hvad gør vi med det ? Det er indlysende nødvendigt at få lavet disse hurtigst muligt

**Comment by perkaspersen** [comment]
Hej Bo, det er også mig som har lead på færdiggørelse af dokumentation, og jeg fortsætter i denne uge med begge dokumenter (input data og vejledning i brug af model).

**Comment by bvthomsen** [comment]
Bo laver selve dokumentet og udfylder så meget af dette vha. oplysninger i parameter databasen. Per skriver afsnit med modelbeskrivelser

**Comment by bvthomsen** [comment]
Installation, brugerdokumentation og Administrator dokumentation færdiggjort
